---
name: dbot apps
env: 
  SayHelloGroup: 
    value: dev81,local,dev63
remotes: 
  dev63: 
    host: 192.168.1.63
    user: tianshuo
  dev81: 
    host: 192.168.1.81
    user: root
jobs:
  install:
    commands:
      - type: job
        config: ../examples/etcd/main.yml
        exec: initEtcdNodeCA
      - type: job
        config: ../examples/etcd/main.yml
        exec: initEtcdClientCA
  test:
    commands:
      - type: js
        on: dev81
        exec: |
          (function(name) {
            dbot.Log("hello log " + name)
            dbot.Error("hello error " + name)
            dbot.Command({
              exec: 'echo "hello uu"',
              inputs: [
                "hello",
                "world",
              ],
              env: {
                TestEnv: "you",
              },
            })
          }) ("world")
      - exec: echo "hello"
      - exec: echo "hello"
