---
name: dbot apps
jobs:
  install:
    commands:
      - type: job
        config: ../examples/etcd/main.yml
        exec: initEtcdNodeCA
      - type: job
        config: ../examples/etcd/main.yml
        exec: initEtcdClientCA