---
name: dbot apps
env: 
  SayHelloGroup: 
    value: dev81,local,dev63
remotes: 
  dev63: 
    host: 192.168.1.63
    user: tianshuo
  dev81: 
    host: 192.168.1.81
    user: root
jobs:
  install:
    commands:
      - type: job
        config: ../examples/etcd/main.yml
        exec: initEtcdNodeCA
      - type: job
        config: ../examples/etcd/main.yml
        exec: initEtcdClientCA
  test:
    commands:
      - exec: echo "hello"
        on: ${SayHelloGroup}

