---
name: dbot apps
jobs:
  createCA:
    env: 
      OutputDir: 
        value: ${ConfigDir}/data
        desc: the ca output directory
      SSL_EXPIRE_DAYS:
        value: 109500
      SSL_KEY_BITS:
        value: 4096
      SSL_C:
        value: CN
        desc: Country Name (2 letter code)
      SSL_ST:
        value: Zhejiang
        desc: State or Province Name (full name)
      SSL_L:
        value: Hangzhou
        desc: Locality Name (eg, city)
      SSL_O:
        value: rpc cloud co. Ltd.
        desc: Organization Name (eg, company)
      SSL_OU:
        value: IT
        desc: Organizational Unit Name (eg, section)
      SSL_CN:
        value: com.rpccloud.dev
        desc: Common Name (eg, fully qualified host name)
    commands:
      - exec: mkdir ${OutputDir}
      - exec: vi ${OutputDir}/ca.cnf
        inputs: 
          - i
          - "[ req ]\n"
          - "default_bits           = ${SSL_KEY_BITS}\n"
          - "distinguished_name     = req_distinguished_name\n"
          - "prompt                 = no\n"
          - "[ req_distinguished_name ]\n"
          - "C                      = ${SSL_C}\n"
          - "ST                     = ${SSL_ST}\n"
          - "L                      = ${SSL_L}\n"
          - "O                      = ${SSL_O}\n"
          - "OU                     = ${SSL_OU}\n"
          - "CN                     = ${SSL_CN}\n"
          - "[ v3_ca ]\n"
          - "keyUsage = critical, keyCertSign, cRLSign\n"
          - "basicConstraints = critical, CA:TRUE, pathlen:2\n"
          - "subjectKeyIdentifier = hash\n"
          - "authorityKeyIdentifier = keyid:always\n"
          - "${KeyESC}:wq${KeyEnter}\n"
      - exec: openssl genrsa -out ${OutputDir}/ca-key.pem ${SSL_KEY_BITS}
      - exec: openssl req -x509 -new -nodes -config ${OutputDir}/ca.cnf 
              -extensions v3_ca -key ${OutputDir}/ca-key.pem 
              -days ${SSL_EXPIRE_DAYS} -out ${OutputDir}/ca.pem
